# Generated by Django 5.2.4 on 2026-10-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_clinic_plan_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='share_clients',
            field=models.BooleanField(default=True),
        ),
    ]
