# Generated by Django 5.2.4 on 2025-07-17 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=50)),
                ('protein', models.FloatField()),
                ('carb', models.FloatField()),
                ('fat', models.FloatField()),
                ('food_type', models.CharField(choices=[('carb', 'Carb'), ('protein', 'Protein'), ('fat', 'Fat'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_ar', models.CharField(blank=True, max_length=50, null=True)),
                ('multiplying_factor', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('height', models.FloatField(help_text='Height in cm')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('goal', models.CharField(blank=True, choices=[('gain', 'Weight Gain'), ('loss', 'Weight Loss'), ('maintain', 'Maintain'), ('', 'Empty')], default='', max_length=10)),
                ('work_style', models.CharField(choices=[('bed_bound', 'Chair bound/bed bound'), ('seated_static', 'Seated work with no option of moving, no activity'), ('seated_moving', 'Seated work with requirement to moving a little'), ('standing', 'Standing work (e.g., housework, shop assistant)'), ('sport', 'Significant amounts of sport'), ('strenuous', 'Strenuous work or highly active')], max_length=20)),
                ('bmr', models.FloatField(editable=False)),
                ('activity_value', models.FloatField(editable=False, null=True)),
                ('target_calories', models.FloatField(editable=False, null=True)),
                ('target_protein', models.FloatField(editable=False, null=True)),
                ('target_carb', models.FloatField(editable=False, null=True)),
                ('target_fat', models.FloatField(editable=False, null=True)),
                ('smm', models.FloatField(blank=True, null=True)),
                ('pbf', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfileRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('goal', models.CharField(blank=True, max_length=20)),
                ('smm', models.FloatField(blank=True, null=True)),
                ('pbf', models.FloatField(blank=True, null=True)),
                ('work_style', models.CharField(blank=True, max_length=50)),
                ('bmr', models.FloatField(blank=True, null=True)),
                ('calorie_target', models.FloatField(blank=True, null=True)),
                ('target_protein', models.FloatField(blank=True, null=True)),
                ('target_carb', models.FloatField(blank=True, null=True)),
                ('target_fat', models.FloatField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_revisions', to='nutrition.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_protein', models.FloatField()),
                ('total_carb', models.FloatField()),
                ('total_fat', models.FloatField()),
                ('missing_protein', models.FloatField(default=0)),
                ('missing_carb', models.FloatField(default=0)),
                ('missing_fat', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='nutrition.clientprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_diet_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DietItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('carb', 'Carb'), ('protein', 'Protein'), ('fat', 'Fat')], max_length=10)),
                ('quantity', models.IntegerField(default=1, help_text='Number of servings (default = 1)')),
                ('protein', models.FloatField()),
                ('carb', models.FloatField()),
                ('fat', models.FloatField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.dietplan')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.fooditem')),
            ],
        ),
    ]
