# Generated by Django 5.2.4 on 2025-08-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_bmrformula_bmractivitymultiplier_bmrgenderformula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='dietitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='diet_items', to='nutrition.tag'),
        ),
    ]
