# Generated by Django 5.2.4 on 2025-09-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_detailedprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='name',
            field=models.CharField(default='Default Diet Plan', max_length=255),
        ),
    ]
