# Generated by Django 5.2.4 on 2025-09-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_dietplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='carb_percentage',
            field=models.FloatField(blank=True, help_text='Percentage of carbs', null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='fat_percentage',
            field=models.FloatField(blank=True, help_text='Percentage of fat', null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='protein_percentage',
            field=models.FloatField(blank=True, help_text='Percentage of protein', null=True),
        ),
    ]
