# Generated by Django 5.2.4 on 2026-10-09 15:25

import django.db.models.deletion
import nutrition.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0013_workout_levels_goals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#1f6f5c', max_length=20)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('timezone', models.CharField(default='Asia/Amman', max_length=50)),
                ('hours', models.JSONField(default=nutrition.models.default_hours)),
                ('break_start', models.CharField(blank=True, default='13:00', max_length=5)),
                ('break_end', models.CharField(blank=True, default='14:00', max_length=5)),
                ('slot_minutes', models.PositiveIntegerField(default=30)),
                ('currency', models.CharField(default='JOD', max_length=10)),
                ('pay_online', models.BooleanField(default=False)),
                ('pay_at_clinic', models.BooleanField(default=True)),
                ('booking_open', models.BooleanField(default=True)),
                ('reminders', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, default='', max_length=100)),
                ('minutes', models.PositiveIntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('color', models.CharField(default='#2f5fb3', max_length=20)),
                ('online', models.BooleanField(default=False, help_text='Video call instead of a clinic visit')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='nutrition.calendar')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClientPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('visits', models.PositiveIntegerField(default=4)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='nutrition.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, default='', max_length=100)),
                ('guest_phone', models.CharField(blank=True, default='', max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('attended', 'Attended'), ('no_show', 'No-show'), ('cancelled', 'Cancelled')], default='booked', max_length=10)),
                ('source', models.CharField(default='dietitian', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('pay_method', models.CharField(blank=True, choices=[('', 'Not set'), ('clinic', 'Pay at clinic'), ('online', 'Online')], default='', max_length=10)),
                ('paid', models.BooleanField(default=False)),
                ('paid_via', models.CharField(blank=True, choices=[('', ''), ('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer'), ('online', 'Online'), ('package', 'Package')], default='', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='nutrition.clientprofile')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='nutrition.appointmenttype')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='nutrition.calendar')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='nutrition.clientpackage')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='DayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meals', models.JSONField(blank=True, default=dict)),
                ('water', models.PositiveIntegerField(default=0, help_text='Glasses of 250 ml')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_logs', to='nutrition.clientprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('client', 'date')},
            },
        ),
    ]
