# Generated by Django 5.2.4 on 2026-10-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0014_appointments_client_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedprofile',
            name='exercise_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detailedprofile',
            name='exercise_place',
            field=models.CharField(blank=True, choices=[('Gym', 'Gym'), ('Home', 'Home'), ('Outdoors', 'Outdoors'), ('Sports club', 'Sports club')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detailedprofile',
            name='willing_gym',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailedprofile',
            name='willing_home',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailedprofilerevision',
            name='exercise_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detailedprofilerevision',
            name='exercise_place',
            field=models.CharField(blank=True, choices=[('Gym', 'Gym'), ('Home', 'Home'), ('Outdoors', 'Outdoors'), ('Sports club', 'Sports club')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detailedprofilerevision',
            name='willing_gym',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailedprofilerevision',
            name='willing_home',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
