# Generated by Django 5.2.4 on 2026-10-09 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0015_interview_exercise_place_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='micros',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lab', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_tests', to='nutrition.clientprofile')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BloodResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('ref_low', models.FloatField(blank=True, null=True)),
                ('ref_high', models.FloatField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='nutrition.bloodtest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BloodTestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('data', models.BinaryField()),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='nutrition.bloodtest')),
            ],
        ),
    ]
