# Generated by Django 5.2.4 on 2026-10-09 19:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0016_blood_tests_micros'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slots', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nutrition.appointment')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='nutrition.calendar')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_offers', to='nutrition.clientprofile')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition.appointmenttype')),
            ],
        ),
    ]
