# Generated by Django 5.2.4 on 2026-10-10 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0017_booking_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtestfile',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='nutrition.bloodtest'),
        ),
    ]
