# Generated by Django 5.2.4 on 2026-10-10 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0018_blood_test_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('section', models.CharField(blank=True, max_length=50)),
                ('section_ar', models.CharField(blank=True, max_length=50)),
                ('servings', models.PositiveSmallIntegerField(default=1)),
                ('photo', models.CharField(blank=True, max_length=120)),
                ('is_treat', models.BooleanField(default=False)),
                ('has_pork', models.BooleanField(default=False)),
                ('content', models.JSONField(default=dict)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='nutrition.fooditem')),
            ],
        ),
    ]
