# Generated by Django 5.2.4 on 2026-10-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0021_foods_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='allergy_mode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
