# Generated by Django 5.2.4 on 2026-10-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0022_allergy_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='supplements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
