# Generated by Django 5.2.4 on 2026-10-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0023_plan_supplements'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='contact_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
